image: registry.gitlab.com/3li3bdalla/zilrsoft:latest
services:
  - postgres:12
  - redis:6-alpine

stages:
  - build
  - test
  - deploy


variables:
  POSTGRES_DB: zilrsoft
  POSTGRES_USER: zilrsoft
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  DB_CONNECTION: pgsql
  REDIS_HOST: redis
  REDIS_PORT: 6379
  FILESYSTEM_DRIVER: "local"
  BROADCAST_DRIVER: redis
  QUEUE_CONNECTION: redis
  CACHE_DRIVER: redis
  DB_HOST: postgres
  DB_PORT: 5432
  SCOUT_QUEUE: "true"
  DB_DATABASE: zilrsoft
  DB_USERNAME: zilrsoft
  DB_PASSWORD: ""

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - vendor/

build:
  stage: build
  script:
    - docker-php-ext-install soap
    # Install Composer dependencies
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    # Copy over testing configuration
    - cp .env.example .env

    # Generate an application key, re-cache.
    - php artisan key:generate
    - php artisan config:cache

    - php artisan migrate --env=testing
    # Run database seed
    - php artisan db:seed --env=testing
    # Install Node dependencies
    - npm install
    # ci --cache .npm --prefer-offline --quiet

    # Run npm build
    - npm run dev


test:
  stage: test
  dependencies:
    - build
  script:
    - cp .env.example .env.testing
    - php artisan key:generate --env=testing
    # Run database migrations
    - php artisan migrate --env=testing
    # Run database seed
    - php artisan db:seed --env=testing
    - php artisan config:cache
    - ./vendor/bin/phpstan --no-progress --xdebug
    # run laravel tests
  #    - ./vendor/bin/phpunit
  when: on_success




deploy_prod:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ~/.composer/vendor/bin/envoy run deploy --environment=production --commit="$CI_COMMIT_SHA" --cleanup
  environment:
    name: deployer
    url: https://zilrsoft.com
  when: on_success

  only:
    - master
