version: "3.7"
services:
  app:
    build:
      context: "."
      dockerfile: "./devops/Dev/Dockerfile"
    image: zilrsoft_dev
    container_name: zilrsoft_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8080"
      - "3005:3000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: zilrsoft-db
      DB_PORT: 5432
      DB_DATABASE: zilrsoft
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - zilrsoft
  redis:
    image: redis:6-alpine
    container_name: zilrsoft-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - zilrsoft
  postgres:
    image: postgres:13
    container_name: zilrsoft-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: zilrsoft
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - zilrsoft
    volumes:
     - "./../database/docker:/var/lib/postgresql"
networks:
  zilrsoft:
    driver: bridge
