version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.Dev
    image: zilrsoft
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - zilrsoft
  postgres:
      image: postgres:13
      container_name: db
      restart: unless-stopped
      environment:
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
      networks:
        - zilrsoft
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8009:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - zilrsoft

networks:
  zilrsoft:
    driver: bridge
