version: "3.7"
services:
  app:
    build:
      args:
        user: ali
        uid: 1000
      context: ./
      dockerfile: test.Dockerfile
    image: zilrsoft
    container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - zilrsoft

  db:
    image: postgres:13
    container_name: travellist-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    volumes:
#      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - zilrsoft

  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - zilrsoft

networks:
  zilrsoft:
    driver: bridge

