<?php
//
//	namespace Tests\Feature;
//
//	use App\Account;
//	use App\Manager;
//	use App\Organization;
//	use App\User;
//	use Illuminate\Foundation\Testing\WithFaker;
//	use Tests\TestCase;
//
//	class AccountTest extends TestCase
//	{
//
//		use WithFaker;
//		private $manager;
//
//		/**
//		 * A basic feature test example.
//		 *
//		 * @test
//		 * @return void
//		 */
//		public function toCreate()
//		{
//
//
//			$id = $this->manager->organization->accounts()->inRandomOrder()->first()->id;
//
//			$this->assertInstanceOf(Manager::class,$this->manager);
//			$this->assertInstanceOf(User::class,$this->manager->user);
//			$this->assertIsNumeric($id);
////
//			$response = $this->json('post',route('management.accounts.store'),[
//				'ar_name' => $this->faker->name,
//				'name' => $this->faker->name,
//				'parent_id' => $id
//
//
//			]);
//
////			$response->dump();
//
//			$response->assertStatus(302);
//		}
//
//		protected function setUp():void
//		{
//
//
//			parent::setUp(); // TODO: Change the autogenerated stub
//			$this->manager = auth()->loginUsingId(1);
//		}
//
//		/**
//		* @test
//		 */
//		public function toUpdate()
//		{
//			$account = $this->manager->organization->accounts()->inRandomOrder()->first();
//
//			$this->assertInstanceOf(Account::class,$account);
////
//			$response = $this->json('put',route('management.accounts.update',$account->id),[
//				'ar_name' => $this->faker->name,
//				'name' => $this->faker->name,
//				'parent_id' => $account->parent_id,
//				'is_gateway' =>"true"
//
//
//			]);
//
////			$response->dump();
//
//			$response->assertStatus(302);
//		}
//	}
