<?php

namespace Tests\Feature;

use App\Filter;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CategoryFiltersTest extends TestCase
{
	use WithFaker;
	protected function setUp():void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		auth()->loginUsingId(1);
	}
	
	/**
     * A basic feature test example.
     * @test
     * @return void
     */
    public function toAttachFilters()
    {
    	
    	
    	     $category_id = auth()->user()->organization->categories()->inRandomOrder()->first()->id;
    	     
    	     $filters = auth()->user()->organization->filters;
	    $response = $this->json('patch',route('management.categories.store_filters',$category_id),$filters->toArray());

//	    $response->dump();
	    
	    $response->assertStatus(200);
    }
}
