<?php
//
//	namespace Tests\Feature;
//
//	use Illuminate\Foundation\Testing\WithFaker;
//	use Tests\TestCase;
//
//	class ExpenseTest extends TestCase
//	{
//
//		use WithFaker;
//
//		/**
//		 * A basic feature test example.
//		 *
//		 * @test
//		 * @return void
//		 */
//		public function toCreate()
//		{
//			$response = $this->json('post',route('management.expenses.store'),[
//				'name' => $this->faker->name,
//				'ar_name' => $this->faker->name,
//				'appear_in_purchase' => true,
//				'appear_in_sale' => true
//			]);
//
////			$response->dump();
//
//			$response->assertStatus(302);
//		}
//
//		protected function setUp():void
//		{
//			parent::setUp(); // TODO: Change the autogenerated stub
//			auth()->loginUsingId(1);
//		}
//	}
