<?php
	
	namespace Tests\Feature;
	
	use Illuminate\Foundation\Testing\WithFaker;
	use Tests\TestCase;
	
	class ItemTest extends TestCase
	{
		
		use WithFaker;
		
		/**
		 * A basic feature test example.
		 *
		 * @test
		 * @return void
		 */
		public function toCreate()
		{
			$category_id = auth()->user()->organization->categories()->inRandomOrder()->first()->id;
			
			
			
			$data = [
				'name' => $this->faker->name,
				'ar_name' => $this->faker->name,
				'barcode' => $this->faker->numerify(),
				'is_fixed_price' => $this->faker->boolean,
				'is_has_vtp' => true,
				'is_has_vts' => true,
				'is_need_serial' => false,
				'is_service' => $this->faker->boolean,
				'vtp' => 5,
				'vts' => 5,
				'price' => 95.24,
				'price_with_tax' => 100,
				'category_id' => $category_id
			];
			$response = $this->json('post',
				route('management.items.store'),$data);
			
			//$response->dump();
			
			$response->assertStatus(201);
			
		}
		
		protected function setUp():void
		{
			parent::setUp(); // TODO: Change the autogenerated stub
			auth()->loginUsingId(1);
		}
	}
