<?php
//
//	namespace Tests\Feature;
//
//	use App\User;
//	use Illuminate\Foundation\Testing\WithFaker;
//	use Tests\TestCase;
//
//	class ItemTest extends TestCase
//	{
//
//		use WithFaker;
//
//		/**
//		 * A basic feature test example.
//		 *
//		 * @test
//		 * @return void
//		 */
//		public function toCreate()
//		{
//			for ($i = 0;$i < 10;$i++){
//				$category_id = auth()->user()->organization->categories()->inRandomOrder()->first()->id;
//
//				$is_expense = false;
////				if ($i % 1 != 0){
//					$is_expense = $this->faker->boolean;
////				}
//				$data = [
//					'name' => $this->faker->name,
//					'ar_name' => $this->faker->name,
//					'barcode' => $this->faker->iban(),
//					'is_fixed_price' => $this->faker->boolean,
//					'is_has_vtp' => true,
//					'is_has_vts' => true,
//					'is_need_serial' => false,
//					'is_service' => $this->faker->boolean,
//					'is_expense' => $is_expense,
//					'expense_vendor_id' => User::where('is_vendor',true)->first()->id,
//					'vtp' => 5,
//					'vts' => 5,
//					'price' => 100,
//					'price_with_tax' => 105,
//					'category_id' => $category_id
//				];
//				$response = $this->json('post',
//					route('management.items.store'),$data);
//
//				//$response->dump();
//
//				$response->assertStatus(201);
//			}
//
//		}
//
//		protected function setUp():void
//		{
//			parent::setUp(); // TODO: Change the autogenerated stub
//			auth()->loginUsingId(1);
//		}
//	}
