<?php
//
//namespace Tests\Feature;
//
//use Illuminate\Foundation\Testing\DatabaseTransactions;
//use Tests\TestCase;
//use Illuminate\Foundation\Testing\WithFaker;
//use Illuminate\Foundation\Testing\RefreshDatabase;
//
//class CategoryTest extends TestCase
//{
//    use WithFaker;
//
//    protected function setUp(): void
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//        auth()->loginUsingId(1);
//    }
//
//
//    /**
//     * A basic feature test example.
//     *
//     * @return void
//     */
//    public function testIfCreationWorksFine()
//    {
//        $response = $this->
//            withHeaders(
//                [
//                    'HTTP_Authorization' => csrf_token(),
//                    'X-Requested-With'=>'XMLHttpRequest'
//                ]
//            )
//
//            ->json('POST','/management/categories',[
//                'name'=>$this->faker->name,
//                'ar_name'=>$this->faker->name,
//                'description'=>$this->faker->name,
//                'ar_description'=>$this->faker->name,
//                'parent_id'=>61,
//                'isClone'=>1,
//                'cloned_category'=>62,
//            ]);
//
////        $response->dump();
//        $response->assertStatus(302);
//
//
//    }
//}
