<?php
//
//namespace Tests\Feature;
//
//use Tests\TestCase;
//use Illuminate\Foundation\Testing\WithFaker;
//use Illuminate\Foundation\Testing\RefreshDatabase;
//
//class FiltersTest extends TestCase
//{
//
//    use WithFaker;
//
//    protected function setUp(): void
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//        auth()->loginUsingId(1);
//    }
//
//
//    /**
//     * A basic feature test example.
//     *
//     * @return void
//     */
//    public function testCreateFilterValue()
//    {
//
//
//        $response =
//            $this->withHeaders(
//                [
//                    'HTTP_Authorization' => csrf_token(),
//                    'X-Requested-With'=>'XMLHttpRequest'
//                ]
//            )
//            ->json('POST','/management/filters/values/create',[
//                'name'=>$this->faker->name,
//                'ar_name'=>$this->faker->name,
//                'filter_id'=>1,
//
//            ]);
////        $response->dump();
//        $response->assertRedirect();
//
//
//    }
//}
