<?php
	
	namespace Tests\Feature;
	
	use Illuminate\Foundation\Testing\WithFaker;
	use Tests\TestCase;
	
	class InvoiceTest extends TestCase
	{
		
		use WithFaker;
		
		/**
		 * A basic feature test example.
		 *
		 * @test
		 * @return void
		 */
		public function toCreateSaleInvoice()
		{

//
			$data = [];
			$response = $this->json('post',
				route('management.sales.store'),$data);
//
//			$response->dump();
//
			$response->assertStatus(200);
		}
		
		protected function setUp():void
		{
			parent::setUp(); // TODO: Change the autogenerated stub
			auth()->loginUsingId(1);
		}
		
	}
