<?php

namespace App\Http\Resources\Entity;

use Illuminate\Http\Resources\Json\JsonResource;

class TransactionResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        $array = parent::toArray($request);
        $array['debit_amount'] =$this->type == 'debit' ? $this->amount : 0;
        $array['credit_amount'] =$this->type == 'credit' ? $this->amount : 0;
        return $array;
    }

    public function with($request)
    {
        return [
          'debit_amount' => $this->type == 'debit' ? $this->amount : 0,
          'credit_amount' => $this->type == 'credit' ? $this->amount : 0,
        ];
//        return parent::with($request); // TODO: Change the autogenerated stub
    }
}
