<?php

namespace App\Enums;
use Spatie\Enum\Laravel\Enum;
/**
 * @method static self invoice_status()
 * @method static self warranty_tracing_received()
 * @method static self warranty_tracing_processing()
 * @method static self warranty_tracing_ready_to_pick_up()
 * @method static self warranty_tracing_picked_up()
 */
class InvoiceItemStatusEnum extends Enum
{
    public static function labels(): array
    {
        return [
            'warranty_tracing_received' => "تم استلام المنتج من العميل",
            'warranty_tracing_processing' => "جاري المعالجة",
            'warranty_tracing_ready_to_pick_up' => "جاهز للتسليم",
            'warranty_tracing_picked_up' => "تم التسليم للعميل",
        ]; // TODO: Change the autogenerated stub
    }
}