{{-- <script src="{{ asset('web_assets/template/js/jquery-3.3.1.min.js')}}"></script>
<script src="{{ asset('web_assets/template/js/bootstrap.min.js')}}"></script>
<script src="{{ asset('web_assets/template/js/jquery-ui.min.js')}}"></script>
<script src="{{ asset('web_assets/template/js/jquery.countdown.min.js')}}"></script>
<script src="{{ asset('web_assets/template/js/jquery.nice-select.min.js')}}"></script>
<script src="{{ asset('web_assets/template/js/jquery.zoom.min.js')}}"></script>
<script src="{{ asset('web_assets/template/js/jquery.dd.min.js')}}"></script>
<script src="{{ asset('web_assets/template/js/jquery.slicknav.js')}}"></script>
<script src="{{ asset('web_assets/template/js/owl.carousel.min.js')}}"></script>
<script src="{{ asset('web_assets/template/js/main.js')}}"></script>
<script src="{{ asset('web_assets/js/web.js') }}"></script> --}}
